application: inlinecssapp
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /.*
  script: main.py
libraries:
    - name: lxml
      version: "2.3"
    - name: django
      version: "1.2"
